import csv
import io
import json
from datetime import datetime

from docx import Document
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfgen import canvas


def export_pdf(title: str, content: str, author: str = "EduAssist", font_path: str | None = None) -> bytes:
    buffer = io.BytesIO()
    c = canvas.Canvas(buffer, pagesize=A4)
    width, height = A4
    left_margin = 20 * mm
    max_text_width = width - 40 * mm

    font_name = "Helvetica"
    if font_path:
        try:
            pdfmetrics.registerFont(TTFont("DejaVu", font_path))
            font_name = "DejaVu"
        except Exception:
            pass

    c.setFont(font_name, 16)
    c.drawString(left_margin, height - 40 * mm, title)
    c.setFont(font_name, 10)
    c.drawString(left_margin, height - 55 * mm, f"Generated: {datetime.now():%Y-%m-%d %H:%M}")
    c.drawString(left_margin, height - 65 * mm, f"Author: {author}")

    y = height - 85 * mm
    c.setFont(font_name, 11)
    for line in content.split("\n"):
        if y < 50:
            c.showPage()
            c.setFont(font_name, 11)
            y = height - 50
        c.drawString(left_margin, y, line[:120])
        y -= 15

    c.save()
    return buffer.getvalue()


def export_markdown(title: str, content: str) -> str:
    return f"# {title}\n\n{content}\n\n---\n*Generated by EduAssist on {datetime.now():%Y-%m-%d %H:%M}*"


def export_json(title: str, content: str, author: str = "EduAssist") -> str:
    return json.dumps({
        "title": title,
        "content": content,
        "author": author,
        "generated_at": datetime.now().isoformat(),
    }, indent=2, ensure_ascii=False)


def export_csv(title: str, content: str) -> str:
    output = io.StringIO()
    writer = csv.writer(output)
    writer.writerow(["title", "content"])
    writer.writerow([title, content])
    try:
        data = json.loads(content)
        if isinstance(data, list) and data and isinstance(data[0], dict):
            output = io.StringIO()
            writer = csv.DictWriter(output, fieldnames=data[0].keys())
            writer.writeheader()
            writer.writerows(data)
    except (json.JSONDecodeError, TypeError):
        pass
    return output.getvalue()


def export_docx(title: str, content: str, author: str = "EduAssist") -> bytes:
    doc = Document()
    doc.add_heading(title, level=1)
    doc.add_paragraph(f"Generated: {datetime.now():%Y-%m-%d %H:%M}")
    doc.add_paragraph(f"Author: {author}")
    doc.add_paragraph("")
    for line in content.split("\n"):
        if line.startswith("# "):
            doc.add_heading(line[2:], level=2)
        elif line.startswith("- ") or line.startswith("* "):
            doc.add_paragraph(line[2:], style="List Bullet")
        else:
            doc.add_paragraph(line)
    buffer = io.BytesIO()
    doc.save(buffer)
    return buffer.getvalue()
